# Generated by Django 5.2.10 on 2026-03-01 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_github_repo', models.BooleanField(default=False)),
                ('github_repo_id', models.CharField(blank=True, max_length=100, null=True)),
                ('github_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('github_default_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('github_language', models.CharField(blank=True, max_length=100, null=True)),
                ('github_topics', models.JSONField(blank=True, null=True)),
                ('github_stars', models.IntegerField(blank=True, null=True)),
                ('github_forks', models.IntegerField(blank=True, null=True)),
                ('github_watchers', models.IntegerField(blank=True, null=True)),
                ('github_license', models.CharField(blank=True, max_length=100, null=True)),
                ('github_last_push', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('is_directory', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
            ],
        ),
    ]
