# Generated by Django 5.2.10 on 2026-03-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='parent',
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='path',
            field=models.CharField(max_length=500),
        ),
    ]
