# Generated by Django 5.2.10 on 2026-03-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_projectfile_name_remove_projectfile_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='file_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
