# Generated by Django 5.2.10 on 2026-03-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectfile_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='file_id',
        ),
    ]
