# Generated by Django 5.2.10 on 2026-03-07 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectfile_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_default_branch',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_forks',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_full_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_language',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_last_push',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_license',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_repo_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_stars',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_topics',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_watchers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_github_repo',
        ),
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('default_branch', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('topics', models.JSONField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('forks', models.IntegerField(blank=True, null=True)),
                ('watchers', models.IntegerField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('last_push', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github', to='projects.project')),
            ],
        ),
    ]
