# Generated by Django 5.2.10 on 2026-05-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneduser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banneduser',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
