# Generated by Django 5.2.10 on 2026-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_streak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='global_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='problems_solved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
