# Generated by Django 5.2.10 on 2026-02-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop', null=True),
        ),
    ]
