# Generated by Django 5.2.10 on 2026-04-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://shorturl.at/d4eKR', null=True),
        ),
    ]
