# Generated by Django 5.2.10 on 2026-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chellange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('tegs', models.CharField(blank=True, max_length=255)),
                ('e_input', models.TextField(blank=True, null=True)),
                ('e_output', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('difficul', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('language', models.CharField(choices=[('py', 'Python'), ('go', 'Go'), ('dart', 'Dart'), ('rs', 'Rust'), ('kt', 'Kotlin'), ('swift', 'Swift'), ('java', 'Java'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('jsx', 'JSX'), ('tsx', 'TSX'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('txt', 'Text'), ('pdf', 'PDF'), ('md', 'Markdown'), ('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV'), ('yaml', 'YAML'), ('yml', 'YML'), ('pem', 'PEM'), ('env', 'Env'), ('sqlite3', 'SQLite3'), ('db', 'Database'), ('sh', 'Shell Script'), ('bat', 'Batch'), ('ini', 'INI')], default='py', max_length=40)),
            ],
        ),
    ]
