# Generated by Django 5.2.10 on 2026-03-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chellange',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
