# Generated by Django 5.2.10 on 2026-03-15 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_chellange_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tegs', models.CharField(blank=True, help_text='Через кому: array, two-pointers', max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('code', models.TextField(blank=True, help_text="Початковий код для типу 'code'", null=True)),
                ('e_input', models.TextField(blank=True, null=True)),
                ('e_output', models.TextField(blank=True, null=True)),
                ('c_type', models.CharField(choices=[('quiz', 'Quiz'), ('code', 'Code'), ('mentor', 'Mentor Check')], default='code', max_length=20)),
                ('difficul', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('language', models.CharField(choices=[('py', 'Python'), ('go', 'Go'), ('dart', 'Dart'), ('rs', 'Rust'), ('kt', 'Kotlin'), ('swift', 'Swift'), ('java', 'Java'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('jsx', 'JSX'), ('tsx', 'TSX'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('md', 'Markdown'), ('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV'), ('yaml', 'YAML'), ('yml', 'YML'), ('pem', 'PEM'), ('env', 'Env'), ('sqlite3', 'SQLite3'), ('db', 'Database'), ('sh', 'Shell Script'), ('bat', 'Batch'), ('ini', 'INI')], default='py', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('submitted', 'Submitted (awaiting review)')], default='not_started', max_length=20)),
                ('submitted_code', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_feedback', models.TextField(blank=True, null=True)),
                ('mentor_score', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='task.challange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at', '-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='Chellange',
        ),
        migrations.AddConstraint(
            model_name='userchallengeprogress',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_user_challenge'),
        ),
    ]
