# Generated by Django 5.2.10 on 2026-04-19 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_challange_userchallengeprogress_delete_chellange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Через кому: easy, python', max_length=255)),
                ('points', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('c_type', models.CharField(choices=[('quiz', 'Quiz'), ('code', 'Code'), ('mentor', 'Mentor Check')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('py', 'Python'), ('go', 'Go'), ('dart', 'Dart'), ('rs', 'Rust'), ('kt', 'Kotlin'), ('swift', 'Swift'), ('java', 'Java'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('jsx', 'JSX'), ('tsx', 'TSX'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('md', 'Markdown'), ('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV'), ('yaml', 'YAML'), ('yml', 'YML'), ('pem', 'PEM'), ('env', 'Env'), ('sqlite3', 'SQLite3'), ('db', 'Database'), ('sh', 'Shell Script'), ('bat', 'Batch'), ('ini', 'INI')], max_length=40)),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('e_input', models.TextField(blank=True, null=True)),
                ('e_output', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('passing_score', models.PositiveIntegerField(default=70)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userchallengeprogress',
            name='unique_user_challenge',
        ),
        migrations.AddField(
            model_name='userchallengeprogress',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userchallengeprogress',
            name='selected_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userchallengeprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('submitted', 'Submitted (awaiting review)')], default='not_started', max_length=30),
        ),
        migrations.AlterField(
            model_name='userchallengeprogress',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='task.challenge'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallengeprogress',
            unique_together={('user', 'challenge')},
        ),
        migrations.AddField(
            model_name='codechallenge',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_challenge', to='task.challenge'),
        ),
        migrations.AddField(
            model_name='quizchallenge',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_challenge', to='task.challenge'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='task.quizchallenge'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='task.quizquestion'),
        ),
        migrations.DeleteModel(
            name='Challange',
        ),
    ]
