# Generated by Django 5.2.10 on 2026-05-05 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_challenge_codechallenge_quizanswer_quizchallenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-created_at'], 'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.AddField(
            model_name='challenge',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchallengeprogress',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='c_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('code', 'Code'), ('mentor', 'Mentor Check')], max_length=20, verbose_name='Тип завдання'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(verbose_name='Опис завдання'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Кількість балів за виконання завдання', verbose_name='Бали'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва завдання'),
        ),
        migrations.AlterField(
            model_name='quizchallenge',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, help_text='Мінімальний бал для проходження квізу'),
        ),
    ]
