# Generated by Django 5.2.10 on 2026-05-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_challenge_options_challenge_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codechallenge',
            name='language',
        ),
        migrations.AddField(
            model_name='challenge',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('go', 'Go'), ('dart', 'Dart'), ('rs', 'Rust'), ('kt', 'Kotlin'), ('swift', 'Swift'), ('java', 'Java'), ('js', 'JavaScript'), ('ts', 'TypeScript'), ('jsx', 'JSX'), ('tsx', 'TSX'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('md', 'Markdown'), ('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV'), ('yaml', 'YAML'), ('yml', 'YML'), ('pem', 'PEM'), ('env', 'Env'), ('sqlite3', 'SQLite3'), ('db', 'Database'), ('sh', 'Shell Script'), ('bat', 'Batch'), ('ini', 'INI')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
