# Generated by Django 5.2.10 on 2026-04-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_level_alter_course_tegs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('web', 'Web Development'), ('mobile', 'Mobile Development'), ('data', 'Data Science'), ('algo', 'Algorithms & Data Structures'), ('devops', 'DevOps & Infrastructure'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
