# Generated by Django 5.2.10 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
