# Generated by Django 5.2.10 on 2026-04-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_unlocked',
        ),
    ]
