# Generated by Django 5.2.10 on 2026-04-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_is_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
