# Generated by Django 5.2.10 on 2026-04-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_userlessonprogress_is_unlocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
    ]
