# Generated by Django 5.2.10 on 2026-05-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_options_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tegs',
            new_name='tags',
        ),
    ]
