# Generated by Django 5.2.10 on 2026-05-05 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forum', '0002_alter_post_options_comment_dislikes_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.PositiveIntegerField(default=0, help_text='Глибина коментаря в гілці'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['depth'], name='forum_comme_depth_43acd8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='forum_post_created_543ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['channel', '-created_at'], name='forum_post_channel_bd23ad_idx'),
        ),
    ]
